lists/urls.py
"""
lists app URL Configuration
"""
from django.urls import path

from . import views

urlpatterns = [
    path('new', views.new_list, name='new_list'),
    path('<int:list_id>/', views.view_list, name='view_list'),
    path('<int:list_id>/add_item', views.add_item, name='add_item'),
]

superlists/urls.py
# from django.contrib import admin
from django.urls import include, path

from lists import views as lists_views

urlpatterns = [
    path('', lists_views.home_page, name='home'),
    path('lists/', include('lists.urls')),
    # path('admin/', admin.site.urls),
]

lists/models.py
"""
The models for the list app
"""
from django.db import models

class Item(models.Model):
    """
    Model that holds a single to-do list item
    """
    text = models.TextField(default='')
    list = models.ForeignKey('List', default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class List (models.Model):
    """
    Model that holds a whole to-do-list
    """

    def __str__(self):
        return f'list {self.id}'

lists/views.py
"""
Views for the lists app of superlists
"""
# from django.http import HttpResponse
from django.shortcuts import redirect, render

from lists.models import Item, List

def home_page(request):
    """
    View to render our home page
    """
    # if request.method == 'POST':
    #     Item.objects.create(text=request.POST['item_text'])
    #     return redirect('/lists/the-only-list/')
    return render(request, 'lists/home.html')

def new_list(request):
    """
    View to render a new list page
    """
    the_list = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=the_list)
    return redirect(f'/lists/{the_list.id}/')

def view_list(request, list_id):
    """
    View to render a list of to-do items
    """
    the_list = List.objects.get(id=list_id)
    # items = Item.objects.filter(list=the_list)
    return render(request, 'lists/list.html', {'list': the_list})

def add_item(request, list_id):
    """
    View to add an item to an existing list
    """
    the_list = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=the_list)
    return redirect(f'/lists/{the_list.id}/')

lists/templates/lists/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To-Do Lists</title>
    <link rel="stylesheet" href="/static/lists/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/lists/base.css">
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3 jumbotron">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock header_text %}</h1>
            <form action="{% block form_action %}{% endblock form_action %}" method="post">
              {% csrf_token %}
              <input type="text" name="item_text" id="id_new_item"
                class="form-control-lg"
                placeholder="Enter a to-do item" />
            </form>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 offset-md-3">
          {% block table %}
          {% endblock table %}
        </div>
      </div>
    </div>
  </body>

</html>

lists/templates/lists/home.html
{% extends "lists/base.html" %}

{% block header_text %}Start a New To-Do List{% endblock header_text %}

{% block form_action %}/lists/new{% endblock form_action %}

lists/templates/lists/list.html
{% extends "lists/base.html" %}

{% block header_text %}Your To-Do List{% endblock header_text %}

{% block form_action %}/lists/{{ list.id }}/add_item{% endblock form_action %}

{% block table %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
      <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock table %}